FROM python:3.9-slim
WORKDIR /app
COPY PLC_hmi.py /app/PLC_hmi.py
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["python", "PLC_hmi.py"]